const waBase='https://wa.me/918421218824';
const waContact=`${waBase}?text=${encodeURIComponent('Hello, I would like to contact RootPromptNext Learning.')}`;
const navItems=[['Home','index.html'],['About','about.html'],['Courses','courses.html'],['Services','services.html'],['Contact','contact.html']];
const trainers=[
 {id:'prayag',name:'Prayag Sangode',role:'Senior Technical Architect',image:'assets/trainers/prayag.jpg',linkedin:'https://www.linkedin.com/in/prayag-sangode-41737318/',courses:['DevOps BootCamp','DevOps Infrastructure Foundation','DevOps Application Deployment']},
 {id:'dinesh',name:'Dinesh M. Bhoyar',role:'Senior Technical Architect | Engineering Leader',image:'assets/trainers/dinesh.jpg',linkedin:'https://www.linkedin.com/in/dinesh-m-bhoyar/',courses:['Go Lang','Python']},
 {id:'arsalan',name:'Arsalan Adil',role:'Practice Manager & Principal Consultant',image:'assets/trainers/arsalan.jpg',linkedin:'https://www.linkedin.com/in/mohammad-arsalan-adil-211167190/',courses:['Data Engineering using Snowflakes']}
];
const courses=[
 {title:'DevOps BootCamp',description:'A broad, hands-on curriculum spanning cloud, automation, containers, CI/CD, DevSecOps, and projects.',href:'https://rootpromptnext.com/devops-bootcamp.html',icon:'01',live:true,trainer:'prayag'},
 {title:'DevOps Infrastructure Foundation',description:'Build a foundation in Linux, AWS, Ansible, and Terraform, then apply it to AWS infrastructure.',href:'https://rootpromptnext.com/devops-infra-foundation.html',icon:'02',live:true,trainer:'prayag'},
 {title:'DevOps Application Deployment',description:'Learn application delivery with Git, Docker, Kubernetes, Jenkins, observability, GitOps, and security topics.',href:'https://rootpromptnext.com/devops-app-deploy.html',icon:'03',live:true,trainer:'prayag'},
 {title:'Data Engineering using Snowflakes',description:'Course details will be shared when this program is available.',href:'#',icon:'04',live:false,trainer:'arsalan'},
 {title:'Go Lang',description:'Course details will be shared when this program is available.',href:'#',icon:'05',live:false,trainer:'dinesh'},
 {title:'Python',description:'Course details will be shared when this program is available.',href:'#',icon:'06',live:false,trainer:'dinesh'}
];
function header(){let current=location.pathname.split('/').pop()||'index.html';return `<a class="skip" href="#main">Skip to main content</a><div class="topline"></div><header class="site-header"><div class="wrap nav"><a class="brand" href="index.html" aria-label="RootPromptNext Learning home"><img class="brand-logo" src="assets/rpn-transparent2-384x97.png" alt="RootPromptNext Learning"></a><button class="nav-toggle" type="button" aria-label="Open navigation" aria-expanded="false">☰</button><nav class="nav-links" aria-label="Main navigation">${navItems.map(([n,h])=>`<a href="${h}" ${current===h?'aria-current="page"':''}>${n}</a>`).join('')}<a class="btn small" href="contact.html#register">Register</a></nav></div></header>`}
function footer(){return `<footer class="footer"><div class="wrap"><div class="footer-grid"><div><a class="brand" href="index.html" style="color:white"><img class="brand-logo brand-logo-footer" src="assets/rpn-transparent2-384x97.png" alt="RootPromptNext Learning"></a><p>RootPromptNext Learning empowers individuals with job-oriented courses crafted by industry experts. Focused on practical skills and real-world projects.</p><p>Practical learning for DevOps, Cloud, and Automation.</p></div><div><h3>Quick Links</h3><ul class="footer-links">${navItems.map(([n,h])=>`<li><a href="${h}">${n}</a></li>`).join('')}</ul></div><div><h3>Contact</h3><ul class="footer-links"><li><a href="${waContact}">WhatsApp: +91 842 121 8824</a></li><li>rootpromptnext@gmail.com</li><li>C604, Gurukrupa Astter, Near Kharadi, Pune 411 014</li></ul></div><div><h3>Terms &amp; Policies</h3><ul class="footer-links"><li><a href="privacy-policy.html">Privacy Policy</a></li><li><a href="terms-and-conditions.html">Terms and Conditions</a></li><li><a href="refund-policy.html">Refund Policy</a></li></ul></div></div><div class="copyright">© RootPromptNext (OPC) Pvt Ltd. All Rights Reserved.</div></div></footer>`}
function linkedInIcon(){return `<svg class="linkedin-icon" viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M20.45 2H3.55C2.69 2 2 2.68 2 3.52v16.96c0 .84.69 1.52 1.55 1.52h16.9c.85 0 1.55-.68 1.55-1.52V3.52c0-.84-.7-1.52-1.55-1.52ZM7.34 18.34H4.4V9.01h2.94v9.33ZM5.87 7.74a1.7 1.7 0 1 1 0-3.4 1.7 1.7 0 0 1 0 3.4Zm12.47 10.6H15.4v-4.54c0-1.08-.02-2.47-1.5-2.47-1.5 0-1.73 1.17-1.73 2.39v4.62H9.23V9.01h2.82v1.27h.04c.39-.73 1.35-1.5 2.78-1.5 2.98 0 3.53 1.96 3.53 4.5v5.06Z"/></svg>`}
function trainerById(id){return trainers.find(t=>t.id===id)}
function trainerAvatar(t){return `<div class="trainer-avatar"><img src="${t.image}" alt="Photo of ${t.name}" width="160" height="160" loading="lazy"></div>`}
function trainerCard(t){return `<article class="trainer-card">${trainerAvatar(t)}<div class="trainer-copy"><h3>${t.name}</h3><p class="trainer-role">${t.role}</p><a class="linkedin-link" href="${t.linkedin}" target="_blank" rel="noopener noreferrer">${linkedInIcon()} View LinkedIn profile</a></div><p class="trainer-courses"><strong>Courses:</strong> ${t.courses.join(' · ')}</p></article>`}
function trainerCards(){return trainers.map(trainerCard).join('')}
function courseCards(){return courses.map(c=>{const t=trainerById(c.trainer);return `<article class="card"><div class="card-icon" aria-hidden="true">${c.icon}</div><span class="badge ${c.live?'live':''}">${c.live?'Available':'Coming soon'}</span><h3>${c.title}</h3><p>${c.description}</p><p class="course-trainer">Trainer: <a href="${t.linkedin}" target="_blank" rel="noopener noreferrer">${linkedInIcon()} ${t.name}</a></p>${c.live?`<a class="card-action" href="${c.href}">Know more <span aria-hidden="true">→</span></a>`:`<span class="card-action" aria-label="${c.title}, coming soon">Coming soon</span>`}</article>`}).join('')}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-site-header]').forEach(x=>x.innerHTML=header());document.querySelectorAll('[data-site-footer]').forEach(x=>x.innerHTML=footer());document.querySelectorAll('[data-course-cards]').forEach(x=>x.innerHTML=courseCards());document.querySelectorAll('[data-trainers]').forEach(x=>x.innerHTML=trainerCards());document.querySelectorAll('[data-trainer]').forEach(x=>{const t=trainerById(x.dataset.trainer);if(t)x.innerHTML=`<div class="trainer-feature">${trainerAvatar(t)}<div><span class="eyebrow">Course instructor</span><h2>${t.name}</h2><p class="lead">${t.role}</p><a class="linkedin-link" href="${t.linkedin}" target="_blank" rel="noopener noreferrer">${linkedInIcon()} View LinkedIn profile</a></div></div>`});const t=document.querySelector('.nav-toggle');if(t)t.addEventListener('click',()=>{let n=document.querySelector('.nav-links'),open=n.classList.toggle('open');t.setAttribute('aria-expanded',String(open));t.setAttribute('aria-label',open?'Close navigation':'Open navigation')});const f=document.querySelector('#registration-form');if(f)f.addEventListener('submit',e=>{e.preventDefault();if(!f.reportValidity())return;const d=new FormData(f);const message=encodeURIComponent(`Hello, I would like to register my interest.\nName: ${d.get('name')}\nEmail: ${d.get('email')}\nPhone: ${d.get('phone')}\nCourse: ${d.get('course')}\nMessage: ${d.get('message')||''}`);document.querySelector('#form-status').textContent='Opening WhatsApp with your enquiry. Review the message and send it to complete your request.';window.open(`${waBase}?text=${message}`,'_blank','noopener')})});



